{% set name = "smirnoff-plugins" %}
{% set version = "2024.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 08705fcefbc0fb1d07273ba3c5aff7dc2e343b49c8e00bb60bb91f83db3d6034

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - setuptools
  run:
    - python >=3.10
    - openff-toolkit-base >=0.16
    - openff-interchange-base =0.4
    - numpy
    - openmm

test:
  imports:
    - smirnoff_plugins

about:
  home: https://github.com/openforcefield/smirnoff-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Custom classes for extending SMIRNOFF force fields.
  description: |
    A framework that provides chasses which enable the use of custom force field
    functional forms in SMIRNOFF force fields via plugins in OpenFF infrastructure
  doc_url: https://github.com/openforcefield/smirnoff-plugins
  dev_url: https://github.com/openforcefield/smirnoff-plugins

extra:
  recipe-maintainers:
    - simonboothroyd
    - jthorton
    - mattwthompson
