{% set name = "smirnoff-plugins" %}
{% set version = "2024.01.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 835ed5bdccdb814ce88cbb1bbc5fcc4197265f5ed4993790ee57c4d84422bfeb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.13
    - pip
  run:
    - python >=3.9
    - openff-toolkit-base >=0.14.3
    - openff-interchange-base >=0.3.18
    - numpy
    - openmm

test:
  imports:
    - smirnoff_plugins

about:
  home: https://github.com/openforcefield/smirnoff-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Custom classes for extending SMIRNOFF force fields.
  description: |
    A framework that provides chasses which enable the use of custom force field
    functional forms in SMIRNOFF force fields via plugins in OpenFF infrastructure
  doc_url: https://github.com/openforcefield/smirnoff-plugins
  dev_url: https://github.com/openforcefield/smirnoff-plugins

extra:
  recipe-maintainers:
    - simonboothroyd
    - jthorton
    - mattwthompson
