{% set name = "smirnoff-plugins" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d8f59c06d61b913246dabb55cd7d76eaae1c2eb45f8b0e25df851d1a72b92023

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - openff-toolkit-base >=0.12.1
    - openff-interchange-base >=0.3
    - numpy
    - openmm

test:
  imports:
    - smirnoff_plugins

about:
  home: https://github.com/openforcefield/smirnoff-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Custom parameter handlers for extending SMIRNOFF force fields.
  description: |
    A framework that provides parameter handlers that enable using custom force field
    functional forms in SMIRNOFF based force fields via the OpenFF toolkits built-in
    plugin system.
  doc_url: https://github.com/openforcefield/smirnoff-plugins
  dev_url: https://github.com/openforcefield/smirnoff-plugins

extra:
  recipe-maintainers:
    - simonboothroyd
    - jthorton
    - mattwthompson
